id: P008272
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00KG01653
  title: དབུ་མའི་ལྟ་མགུར་ཡང་དག་ལྟ་བའི་འོད་འབྱིན
  author: ''
  volumes:
    db24d47d183d4c688a6936ae8b5e1125:
      image_group_id: I00KG02965
      title: ''
      volume_number: 1
      total_pages: 12
      base_file: v001.txt
